# Generated by Django 4.2.5 on 2023-09-16 00:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=20, unique=True, verbose_name="Name of Departments")),
                ("description", models.CharField(max_length=1024, verbose_name="Brief description of the Department")),
            ],
            options={
                "db_table": "departments",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                ("id", models.CharField(primary_key=True, serialize=False, unique=True)),
                ("name", models.CharField(max_length=20, unique=True, verbose_name="Name of Departments")),
                ("description", models.CharField(max_length=1024, verbose_name="Brief description of the Department")),
            ],
            options={
                "db_table": "units",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AddField(
            model_name="user",
            name="card_no",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="dob",
            field=models.DateField(
                default=datetime.datetime(2023, 9, 16, 1, 53, 7, 984679), verbose_name="Date of Birth"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="First Name", max_length=50, verbose_name="First Name of User"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Last Name", max_length=50, verbose_name="Last name of User"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="marital_status",
            field=models.CharField(
                choices=[("M", "Married"), ("S", "Single")], default="S", verbose_name="Marital Status"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="middle_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="Middle name of User"),
        ),
        migrations.AddField(
            model_name="user",
            name="occupation",
            field=models.CharField(
                choices=[
                    ("Civil Servant", "Civil Servant"),
                    ("Business Owner", "Business Owner"),
                    ("Trader", "Trader"),
                    ("Student", "Student"),
                    ("Unemployed", "Unemployed"),
                ],
                default="Student",
                verbose_name="User Occupation",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="1234567890", max_length=20, verbose_name="User Phone Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="sex",
            field=models.CharField(choices=[("M", "Male"), ("F", "Female")], default="M", verbose_name="Gender"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="User Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(verbose_name="User Password"),
        ),
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.department"),
        ),
        migrations.AddField(
            model_name="user",
            name="unit",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="users.unit"),
        ),
    ]
